TebLocalPlannerROS:

 odom_topic: wheel_odom
 map_frame: odom

 publish_feedback: True
 # Trajectory

 teb_autosize: True
 dt_ref: 0.9 #0.65 #0.45 2023-10-21 #0.4
 dt_hysteresis: 0.33 #0.055 #0.7 # 0.2 2023-10-20
 allow_init_with_backwards_motion: true #!!!!!!
 global_plan_overwrite_orientation: false  #True 
 max_global_plan_lookahead_dist: 5.0 #NEED TO CHANGE # 3.0
 feasibility_check_no_poses: 2 #5
 
 # Robot

 cmd_angle_instead_rotvel: False
 max_vel_x:  0.45 #0.45 #0.3
 max_vel_y:  0.0 
 max_vel_x_backwards: 0.4 #0.4 # 0.3
 max_vel_theta:  0.11 #0.11 # 1.5
 acc_lim_x: 0.25 #0.25 #0.3 #0.2
 acc_lim_y: 0.0 ##0.2
 acc_lim_theta: 0.11 # 0.3 # by Roy
 min_turning_radius: 0.9 #1.3 #Ackermann #0.4 
 wheelbase: 0.53 #Ackermann #0.4
 footprint_model:  #types: "point", "circular", "two_circles", "line", "polygon"
    type: "polygon"
    #radius: 0.20 # for type "circular"
    #vertices: [[1.75,-0.575],[1.75,0.575],[-0.25,0.575],[-0.25,0.3],[-0.75,0.3],[-0.75,-0.3],[-0.25,-0.3],[-0.25,-0.575]]
    vertices: [[-0.15, -0.38],  [-0.15, 0.38],  [0.67,0.38],  [0.67, -0.38]]
 
 
    
# GoalTolerance

 xy_goal_tolerance: 0.049 #0.22 #0.20 #0.1 #Default 0.15
 yaw_goal_tolerance: 0.085 #0.08 #0.1 #0.1 #Default 0.2
 free_goal_vel: False

 # Obstacles

 min_obstacle_dist: 0.7 # 0.7 # 0.8
 inflation_dist: 0.6 #new test
 include_costmap_obstacles: False # 避障參數之一
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 7
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5
 legacy_obstacle_association: False #False

 # Optimization

 no_inner_iterations: 8 # 5  #3
 no_outer_iterations: 6 #4  #2
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 1
 weight_max_vel_theta: 200 # 520 # 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 14 # 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 800 #0.001 # 1
 weight_kinematics_turning_radius: 0.01
 weight_optimaltime: 1
 weight_obstacle: 350 #50
 weight_dynamic_obstacle: 10 # not in use yet
 selection_alternative_time_cost: False # not in use yet
 weight_viapoint: 10 #10
 global_plan_viapoint_sep: 2.0  # 2.5 #5.0 #0.2
 # Homotopy Class Planner

 enable_homotopy_class_planning: False #False
 enable_multithreading: False
 simple_exploration: False
 max_number_classes: 3 # 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False
